package mediasync

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	envExampleFilename = ".env.example"
	envLocalFilename   = ".env.local"
	defaultEnvExample  = `# Shopify Admin API client credentials
SHOPIFY_CLIENT_ID=
SHOPIFY_CLIENT_SECRET=

# Alternative: SHOPIFY_ADMIN_TOKEN=
# Store-scoped forms append _STORE_ID to a supported key.
`
)

type envRuntimeReport struct {
	SchemaVersion int        `json:"schema_version"`
	Command       string     `json:"command"`
	Status        string     `json:"status"`
	ExamplePath   string     `json:"example_path"`
	LocalPath     string     `json:"local_path"`
	SourcePath    string     `json:"source_path,omitempty"`
	WouldWrite    bool       `json:"would_write"`
	Created       bool       `json:"created"`
	Mode          string     `json:"mode,omitempty"`
	Auth          doctorAuth `json:"auth"`
	Problems      []string   `json:"problems"`
	NextAction    string     `json:"next_action"`
}

func runEnvInit(stdout io.Writer, opts commandOptions) error {
	report, err := buildEnvInitReport(opts)
	if writeErr := writeEnvRuntimeReport(stdout, opts.format, report); writeErr != nil {
		return writeErr
	}
	return err
}

func buildEnvInitReport(opts commandOptions) (envRuntimeReport, error) {
	root, err := filepath.Abs(opts.rootPath)
	if err != nil {
		return envRuntimeReport{}, err
	}
	examplePath := filepath.Join(root, envExampleFilename)
	localPath := filepath.Join(root, envLocalFilename)
	report := envRuntimeReport{
		SchemaVersion: 1,
		Command:       "env-init",
		Status:        "PREVIEW_READY",
		ExamplePath:   examplePath,
		LocalPath:     localPath,
		SourcePath:    opts.sourceEnv,
		WouldWrite:    true,
		Problems:      []string{},
		NextAction:    "run env-init without --dry-run",
	}
	if _, err := os.Lstat(localPath); err == nil {
		report.Status = "REFUSED"
		report.WouldWrite = false
		report.Problems = append(report.Problems, ".env.local 已存在，拒绝覆盖")
		report.NextAction = "preserve the existing .env.local or replace it explicitly outside env-init"
		return report, errors.New(".env.local 已存在，env-init 拒绝覆盖")
	} else if !errors.Is(err, os.ErrNotExist) {
		return report, err
	}

	content, values, err := envInitContent(examplePath, opts.sourceEnv)
	if err != nil {
		report.Status = "NEEDS_SETUP"
		report.WouldWrite = false
		report.Problems = append(report.Problems, err.Error())
		report.NextAction = "fix the explicit source file, then rerun env-init"
		return report, err
	}
	if len(values) > 0 {
		report.Auth, _ = diagnoseEnvFileAny(values)
	}
	if opts.dryRun {
		return report, nil
	}
	if err := writeExclusive0600(localPath, content); err != nil {
		report.Status = "FAILED"
		report.WouldWrite = false
		report.Problems = append(report.Problems, "failed to create .env.local")
		return report, err
	}
	report.Status = "CREATED"
	report.Created = true
	report.WouldWrite = false
	report.Mode = "0600"
	report.NextAction = "run env-check, then doctor --env-file .env.local"
	return report, nil
}

func envInitContent(examplePath, sourcePath string) ([]byte, map[string]string, error) {
	if sourcePath == "" {
		raw, err := os.ReadFile(examplePath)
		if err == nil {
			return raw, nil, nil
		}
		if errors.Is(err, os.ErrNotExist) {
			return []byte(defaultEnvExample), nil, nil
		}
		return nil, nil, err
	}
	values, err := readDotEnv(sourcePath)
	if err != nil {
		return nil, nil, fmt.Errorf("explicit source env is not readable: %w", err)
	}
	filtered := map[string]string{}
	for key, value := range values {
		if isShopifyAuthEnvKey(key) {
			if strings.ContainsAny(value, "\r\n") {
				return nil, nil, fmt.Errorf("Shopify env value contains a line break: %s", key)
			}
			filtered[key] = value
		}
	}
	if len(filtered) == 0 {
		return nil, nil, errors.New("explicit source contains no supported Shopify auth variables")
	}
	if _, problems := diagnoseEnvFileAny(filtered); len(problems) > 0 {
		return nil, nil, errors.New(strings.Join(problems, "; "))
	}
	keys := make([]string, 0, len(filtered))
	for key := range filtered {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var builder strings.Builder
	builder.WriteString("# Generated by shopify-media-sync env-init. Do not commit.\n")
	for _, key := range keys {
		fmt.Fprintf(&builder, "%s=%s\n", key, filtered[key])
	}
	return []byte(builder.String()), filtered, nil
}

func writeExclusive0600(path string, content []byte) (err error) {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := file.Close(); err == nil {
			err = closeErr
		}
		if err != nil {
			_ = os.Remove(path)
		}
	}()
	if err = file.Chmod(0o600); err != nil {
		return err
	}
	if _, err = file.Write(content); err != nil {
		return err
	}
	return file.Sync()
}

func runEnvCheck(stdout io.Writer, opts commandOptions) error {
	report, err := buildEnvCheckReport(opts)
	if writeErr := writeEnvRuntimeReport(stdout, opts.format, report); writeErr != nil {
		return writeErr
	}
	return err
}

func buildEnvCheckReport(opts commandOptions) (envRuntimeReport, error) {
	root, err := filepath.Abs(opts.rootPath)
	if err != nil {
		return envRuntimeReport{}, err
	}
	report := envRuntimeReport{
		SchemaVersion: 1,
		Command:       "env-check",
		Status:        "READY",
		ExamplePath:   filepath.Join(root, envExampleFilename),
		LocalPath:     filepath.Join(root, envLocalFilename),
		Problems:      []string{},
		NextAction:    "run doctor --env-file .env.local",
	}
	info, err := os.Stat(report.LocalPath)
	if err != nil || info.IsDir() {
		report.Problems = append(report.Problems, ".env.local is not a readable file")
	} else {
		report.Mode = fmt.Sprintf("%04o", info.Mode().Perm())
		if info.Mode().Perm() != 0o600 {
			report.Problems = append(report.Problems, ".env.local permissions must be exactly 0600")
		}
		values, readErr := readDotEnv(report.LocalPath)
		if readErr != nil {
			report.Problems = append(report.Problems, "failed to parse .env.local")
		} else {
			auth, readProblems := diagnoseEnvFileAny(values)
			report.Auth = auth
			report.Problems = append(report.Problems, readProblems...)
		}
	}
	if len(report.Problems) > 0 {
		report.Status = "NEEDS_SETUP"
		report.NextAction = "fix the reported env runtime problems, then rerun env-check"
		return report, errors.New("env-check found runtime problems")
	}
	return report, nil
}

func diagnoseEnvFileAny(values map[string]string) (doctorAuth, []string) {
	problems := []string{}
	availableSources := map[string]bool{}
	globalID := strings.TrimSpace(values["SHOPIFY_CLIENT_ID"]) != ""
	globalSecret := strings.TrimSpace(values["SHOPIFY_CLIENT_SECRET"]) != ""
	if globalID != globalSecret {
		problems = append(problems, "SHOPIFY_CLIENT_ID and SHOPIFY_CLIENT_SECRET must be configured together")
	} else if globalID {
		availableSources["client_credentials_env_file"] = true
	}
	if strings.TrimSpace(values["SHOPIFY_ADMIN_TOKEN"]) != "" {
		availableSources["admin_token_env_file"] = true
	}

	clientSuffixes := map[string]bool{}
	for key, value := range values {
		if strings.HasPrefix(key, "SHOPIFY_CLIENT_ID_") && strings.TrimSpace(value) != "" {
			clientSuffixes[strings.TrimPrefix(key, "SHOPIFY_CLIENT_ID_")] = true
		}
		if strings.HasPrefix(key, "SHOPIFY_CLIENT_SECRET_") && strings.TrimSpace(value) != "" {
			clientSuffixes[strings.TrimPrefix(key, "SHOPIFY_CLIENT_SECRET_")] = true
		}
		if strings.HasPrefix(key, "SHOPIFY_ADMIN_TOKEN_") && strings.TrimSpace(value) != "" {
			availableSources["per_store_admin_token_env_file"] = true
		}
	}
	for suffix := range clientSuffixes {
		idPresent := strings.TrimSpace(values["SHOPIFY_CLIENT_ID_"+suffix]) != ""
		secretPresent := strings.TrimSpace(values["SHOPIFY_CLIENT_SECRET_"+suffix]) != ""
		if idPresent != secretPresent {
			problems = append(problems, "per-store client ID and client secret must be configured together for "+suffix)
		} else if idPresent {
			availableSources["per_store_client_credentials_env_file"] = true
		}
	}
	if len(problems) > 0 {
		return doctorAuth{Source: "partial_env_file"}, problems
	}
	if len(availableSources) == 0 {
		return doctorAuth{Source: "missing"}, []string{"Shopify auth is unavailable in .env.local"}
	}
	if len(availableSources) == 1 {
		for source := range availableSources {
			return doctorAuth{Available: true, Source: source}, nil
		}
	}
	return doctorAuth{Available: true, Source: "mixed_env_file"}, nil
}

func isShopifyAuthEnvKey(key string) bool {
	for _, exact := range []string{"SHOPIFY_CLIENT_ID", "SHOPIFY_CLIENT_SECRET", "SHOPIFY_ADMIN_TOKEN"} {
		if key == exact {
			return true
		}
		prefix := exact + "_"
		if strings.HasPrefix(key, prefix) && validEnvSuffix(strings.TrimPrefix(key, prefix)) {
			return true
		}
	}
	return false
}

func validEnvSuffix(suffix string) bool {
	if suffix == "" {
		return false
	}
	for _, char := range suffix {
		if (char < 'A' || char > 'Z') && (char < '0' || char > '9') && char != '_' {
			return false
		}
	}
	return true
}

func writeEnvRuntimeReport(stdout io.Writer, format string, report envRuntimeReport) error {
	if format == "json" {
		encoder := json.NewEncoder(stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(report)
	}
	fmt.Fprintf(stdout, "status=%s command=%s local=%s mode=%s\n", report.Status, report.Command, report.LocalPath, report.Mode)
	for _, problem := range report.Problems {
		fmt.Fprintf(stdout, "problem=%s\n", problem)
	}
	fmt.Fprintf(stdout, "next_action=%s\n", report.NextAction)
	return nil
}
